version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      # prod major version updates will be reported in standalone PRs
      prod-minor-versions:
        applies-to: version-updates
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      dev-major-versions:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "major"
      dev-minor-versions:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
